name: build-binaries
on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        package: ["slurm-monitor"]
        python-version: ["3.10"]
      fail-fast: false
    runs-on:  ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: python -m pip install tox

      - name: Build with pyinstaller
        run: |
          tox -e build
          ./dist/$(uname -i)/slurm-monitor system-info

      - name: Build with nuitka
        run: |
          tox -e build-nuitka
          ./dist/$(uname -i)/slurm-monitor system-info
