#!/usr/bin/env bash

if [[ $1 =~ listpids ]]; then
    echo "PID      JOBID    STEPID   LOCALID GLOBALID"
    echo "$PPID  1 batch - -"
    echo "$PPID  2 batch - -"
    echo " No job steps exist on this node."
fi
