#!/usr/bin/bash

SCRIPT_DIR=$(realpath -L $(dirname $0))
response_file_prefix=$SCRIPT_DIR/slurmrestd.response

read input

if [[ $input =~ /nodes ]]; then
    echo $(< $response_file_prefix.nodes)
fi
